### ISSUE TITLE
Week 2: Make bar chart in PowerBi.

### ISSUE THREAD

**Issue by arizvi99** [CubeStatistica/Professional-Training-for-Data-Science-Team-Learners#19]
Please mark as completed:

- [x]  @Berjees100
- [x]  @moniza22
- [x]  @arizvi99
- [x]  @mumairwaseem
- [x]  @qasimbasra

**Comment by arizvi99** [comment]
Not using PowerBI, so not applicable.

**Comment by moniza22** [comment]
Done in Tableau.
