### ISSUE TITLE
Week 1: Install Git Bash in Your Machine.

### ISSUE THREAD

**Issue by Berjees100** [CubeStatistica/Professional-Training-for-Data-Science-Team-Learners#2]

**Comment by Berjees100** [comment]
Please mark done:

- [x] @Berjees100 
- [x] @moniza22 
- [x] @arizvi99 
- [x] @mumairwaseem 
- [x] @qasimbasra

**Comment by arizvi99** [comment]
I am using Mac so I will use the terminal vs using Gitbash.

**Comment by mumairwaseem** [comment]
Done

**Comment by moniza22** [comment]
I am using Mac terminal.
- [x] @moniza22
