### ISSUE TITLE
Week 2: Integrate R Script into PowerBi.

### ISSUE THREAD

**Issue by arizvi99** [CubeStatistica/Professional-Training-for-Data-Science-Team-Learners#25]
Please mark as completed:

- [ ] @Berjees100
- [x]  @moniza22
- [x]  @arizvi99
- [ ]  @mumairwaseem
- [x]  @qasimbasra

**Comment by arizvi99** [comment]
Not using PowerBI, so not applicable.

**Comment by moniza22** [comment]
Don't Know how to do it in Tableau Public as it's currently not allowing for TCP/IP services to integrate R Script.
