### ISSUE TITLE
Week 2: Linked the bookmarks to button in PowerBi.

### ISSUE THREAD

**Issue by arizvi99** [CubeStatistica/Professional-Training-for-Data-Science-Team-Learners#31]
Please mark as completed:

- [x] @Berjees100
- [x]  @moniza22
- [x]  @arizvi99
- [ ]  @mumairwaseem
- [x]  @qasimbasra

**Comment by qasimbasra** [comment]
Integrated actions with button in Tableau which is similar to linking bookmarks to button in PowerBi

**Comment by moniza22** [comment]
bookmarks are not allowed in tableau public
