### ISSUE TITLE
Week 2: Add buttons in Powerbi.

### ISSUE THREAD

**Issue by arizvi99** [CubeStatistica/Professional-Training-for-Data-Science-Team-Learners#32]
Please mark as completed:

- [x] @Berjees100
- [x]  @moniza22
- [x]  @arizvi99
- [ ]  @mumairwaseem
- [x]  @qasimbasra

**Comment by qasimbasra** [comment]
I've done it in Tableau.

**Comment by moniza22** [comment]
Done in Tableau.
