### ISSUE TITLE
Week 2: Make Basic filter of data linked to visualization in PowerBi.

### ISSUE THREAD

**Issue by arizvi99** [CubeStatistica/Professional-Training-for-Data-Science-Team-Learners#43]
Please mark as completed:

- [x] @Berjees100
- [x]  @moniza22
- [x]  @arizvi99
- [ ]  @mumairwaseem
- [x]  @qasimbasra

**Comment by moniza22** [comment]
Done in Tableau

**Comment by qasimbasra** [comment]
Done it in Tableau
