### ISSUE TITLE
Week 2: Publish the dashboard.

### ISSUE THREAD

**Issue by arizvi99** [CubeStatistica/Professional-Training-for-Data-Science-Team-Learners#46]
Please mark as completed:

- [x] @Berjees100
- [x]  @moniza22
- [ ]  @arizvi99
- [x]  @mumairwaseem
- [x]  @qasimbasra

**Comment by arizvi99** [comment]
.

**Comment by moniza22** [comment]
- [x] @moniza22 https://rpubs.com/moniza22/DS_Course_Data_Report

**Comment by qasimbasra** [comment]
https://rpubs.com/qasimbasra/ds-course-data-dashboard
